package Enum;

/**
 *
 * @author Germán M. Anselmo
 */

public enum Nombres {
    JUAN, MARÍA, CARLOS, ANA, LUIS, LAURA, PEDRO, ISABEL, RAÚL, ELENA, JOSÉ, SANDRA, MANUEL, CARMEN, PABLO, PATRICIA, MIGUEL, SOFÍA, FRANCISCO, ANGELA, JAVIER, MARTA, ALEJANDRO, TERESA, ANDRÉS, ROCÍO, RAFAEL, SILVIA, IGNACIO, BEATRIZ, ALBERTO, NATALIA, DIEGO, CRISTINA, VÍCTOR, MONICA, ROBERTO, MERCEDES, FERNANDO, LUCÍA, GABRIEL, EVA, SERGIO, MARINA, JORGE, OLGA, RICARDO, PAULA;
}
