package Enum;

/**
 *
 * @author Germán M. Anselmo
 */

public enum Apellidos {
    ZAPATERO, MONTESINOS, RIVERACORTEZ, DELAMARCA, SANTACRUZ, FERNÁNDEZGARCÍA, MONDRAGÓN, VALDESPINO, SILVESTRE, CHAVARRÍA, DELAVEGA, CORTÉS, TORRESMARTÍNEZ, PÉREZRODRÍGUEZ, GUTIÉRREZCORDERO, NAVARROVÁZQUEZ, LOPEZDELAROSA, SÁNCHEZDELAGO, ROMEROHERRERA, GUERRAOLIVERA, FLORESDÍAZ, MENDOZARAMÍREZ, ALCÁNTARACASTILLO, CRUZSOTO, BENAVIDESGUZMÁN, CAMPOSVERA, CORDEROSÁNCHEZ, BLANCOALONSO, TRUJILLOMARTÍN, GARCÍALEÓN, ORTEGARIVAS, JIMÉNEZPAREDES, HERRERAROMÁN, VELÁZQUEZDOMÍNGUEZ, MEDINAPINEDA, RÍOSMORALES, VALVERDECALDERÓN, CASTELLANOVALENCIA, PÉREZSANJUAN, VARGASARIAS, MARTÍNEZMENDEZ, SANTIAGOROJAS, GÓMEZAGUILAR, AVALOSZÚÑIGA, RAMÍREZPALOMO, JUÁREZBARRIOS, FLORESSÁNCHEZ, DURÁNMIRANDA, CHÁVEZGALLARDO, OTEROMALDONADO, RODRÍGUEZCASTILLO, ESPINOZATOSCAN;
}
