package Enum;

/**
 *
 * @author Germán M. Anselmo
 */

public enum Nombres {
    RAMIRO, MIRIAM, JUAN, MARIA, PEDRO, ANA, LUIS, CARMEN, CARLOS, LAURA, RAUL, ELENA, JOSE, SILVIA, JAVIER, SOFIA, MANUEL, ROSA, MIGUEL, MARTA, ANTONIO, PATRICIA, DIEGO, PAULA, ALBERTO, ISABEL, SERGIO, BEATRIZ, FRANCISCO, MONICA, ANDRES, CRISTINA, ALEJANDRO, NURIA, IGNACIO, EVA, GONZALO, TERESA, RUBEN, ANGELA, OSCAR, MARINA, FERNANDO, ANDREA, DAVID, MARTINA, ROBERTO, SANDRA, ALVARO, PILAR, RAFAEL, LUCIA, PEPELUI;
}
